"""add

Revision ID: 060ff9d7154c
Revises: af4c35bd0dca
Create Date: 2023-09-15 13:44:01.143627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060ff9d7154c'
down_revision: Union[str, None] = 'af4c35bd0dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_table_followed_id_fkey', 'association_table', type_='foreignkey')
    op.drop_constraint('association_table_follower_id_fkey', 'association_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_table', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_table', 'user', ['followed_id'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])

    op.drop_column('post', 'username')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.drop_constraint(None, 'association_table', type_='foreignkey')
    op.create_foreign_key('association_table_follower_id_fkey', 'association_table', 'user', ['follower_id'], ['id'])
    op.create_foreign_key('association_table_followed_id_fkey', 'association_table', 'user', ['followed_id'], ['id'])

    # ### end Alembic commands ###
