"""add chat name

Revision ID: 0e769aa66bdd
Revises: d3d6b858011e
Create Date: 2023-09-30 16:25:07.755425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e769aa66bdd'
down_revision: Union[str, None] = 'd3d6b858011e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.String(), nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('chat', 'name')
    # ### end Alembic commands ###
