"""empty message

Revision ID: d3d6b858011e
Revises: e0e4162a0975
Create Date: 2023-09-19 23:28:24.193777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d6b858011e'
down_revision: Union[str, None] = 'e0e4162a0975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_chat_table_chat_id_fkey', 'association_chat_table', type_='foreignkey')
    op.drop_constraint('association_chat_table_user_id_fkey', 'association_chat_table', type_='foreignkey')
    op.create_foreign_key(None, 'association_chat_table', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_chat_table', 'user', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    op.drop_constraint(None, 'association_chat_table', type_='foreignkey')
    op.drop_constraint(None, 'association_chat_table', type_='foreignkey')
    op.create_foreign_key('association_chat_table_chat_id_fkey', 'association_chat_table', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key('association_chat_table_user_id_fkey', 'association_chat_table', 'user', ['user_id'], ['id'])
