"""dd

Revision ID: fdf9e5eb7fbc
Revises: 060ff9d7154c
Create Date: 2023-09-15 18:57:50.549627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf9e5eb7fbc'
down_revision: Union[str, None] = '060ff9d7154c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#op.create_foreign_key(None, 'post', 'user', ['username'], ['username'], ondelete='CASCADE',onupdate="CASCADE")
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user',sa.Column('username',sa.String(),primary_key = True))
   
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user',sa.Column('username'),primary_key = False)
   
    # ### end Alembic commands ###
